import Header from "@/app/components/Header";
import "@/app/globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "New Blog App",
  description: "Generated by create next app",
  keywords: "restaurant, managment",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Header />
      <body className="max-w-5xl mx-auto py-1">{children}</body>
    </html>
  );
}
